[project]
name = "desafio-indicium-lhnautica"
version = "0.1.0"
description = ""
authors = [
    {name = "Leonardo Farias",email = "leofariasrj25@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.14,<4"
dependencies = [
    "pandas (>=3.0.1,<4.0.0)",
    "duckdb (>=1.5.0,<2.0.0)",
    "jupysql (>=0.11.1,<0.12.0)",
    "jupyter (>=1.1.1,<2.0.0)",
    "duckdb-engine (>=0.17.0,<0.18.0)",
    "toml (>=0.10.2,<0.11.0)",
    "plotly (>=6.6.0,<7.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
